title: evanlinjin.me
tagline: Backend developer for hire.
show_downloads: false
locale:       "en"
theme: jekyll-theme-cayman

author:
  name: Evan Lin
  url: https://github.com/evanlinjin

gems:
  - jekyll-mentions
