title: EVANLINJIN.ME
description: Backend developer for hire.
show_downloads: false
theme: jekyll-theme-cayman

author:
  name: Evan Lin
  url: https://github.com/evanlinjin

gems:
  - jekyll-mentions
